export JAVA_OPTS="$JAVA_OPTS -Ddatabase.driver=org.postgresql.Driver"
export JAVA_OPTS="$JAVA_OPTS -Ddatabase.dialect=org.hibernate.dialect.PostgreSQL9Dialect"
export JAVA_OPTS="$JAVA_OPTS -Dlogging.level.org.springframework=INFO"
export CATALINA_OPTS="$CATALINA_OPTS -Daws.region=us-east-1"
export JAVA_OPTS="$JAVA_OPTS -Ddatabase.portNumber=5431"
export JAVA_OPTS="$JAVA_OPTS -Ddatabase.user=wenzhe"
export JAVA_OPTS="$JAVA_OPTS -Ddatabase.password=Wenzhe7777"
export JAVA_OPTS="$JAVA_OPTS -Ddatabase.url=jdbc:postgresql://172.17.0.2:5431/Car_DB"
export JAVA_OPTS="$JAVA_OPTS -Dserver.port=8080"
export JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=dev"
export JAVA_OPTS="$JAVA_OPTS -Djwt.secret=WENZHE-Ascending"
export JAVA_OPTS="$JAVA_OPTS -Dqueue.name=AscendingCarInsurance"
export JAVA_OPTS="$JAVA_OPTS -Daws.accessKeyId=AKIAYYOUCR3MYIA5HYH5"
export JAVA_OPTS="$JAVA_OPTS -Daws.secretKey=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"


