---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for backend pipeline
Parameters:
  SecurityStack:
    Description: Name of an active CloudFormation stack that contains all roles and SGs resources
    Type: String
    Default: wenzheluo-security-studentqna
  Username:
    Description: Database User
    Type: String
    NoEcho: true
  Password:
    Description: Database Password
    Type: String
    NoEcho: true
  OAuthToken:
    Type: String
    NoEcho: true

Resources:
  UnitTest:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Description: Unit Test before Build and Deployment
      VpcConfig:
        SecurityGroupIds: 
          - sg-0be3ba05fb6a0c322
        Subnets:
          - subnet-0d5a2659e2c1eeb9a
        VpcId: vpc-0efbaeebb938b5df8
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: DB_USERNAME
            Value: !Ref Username
          - Name: DB_URL
            Value: wenzheluo.cofbxnshsp2o.us-east-1.rds.amazonaws.com
          - Name: DB_PASSWORD
            Value: !Ref Password
          - Name: DB_NAME
            Value: studentqna_db
      ServiceRole:
        Fn::ImportValue: !Sub "${SecurityStack}-CodeBuildRole"
      Name:
        Fn::Join:
          - ''
          - - !Ref AWS::StackName
            - '-UnitTest'
      Source:
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                java: corretto17
            pre_build:
              commands:
                - cd mvc
                - ls
                - mvn clean compile flyway:migrate -P unit -Ddb_url=${DB_URL}:5432/${DB_NAME} -Ddb_username=${DB_USERNAME} -Ddb_password=${DB_PASSWORD} -q
            build:
              commands:
                - mvn test -Dspring.profiles.active=unit -Ddatabase.serverName=jdbc:postgresql://${DB_URL}:5432/${DB_NAME} -Ddatabase.username=${DB_USERNAME} -Ddatabase.password=${DB_PASSWORD} -Djwt.expiration=86400 -Djwt.secret=123456789 -q
        GitCloneDepth: 1
        Location: https://github.com/wenzheluo/AscendingBackEndProject.git
        Type: GITHUB
  BuildWarFile:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Description: Build war file
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
      Name:
        Fn::Join:
          - ''
          - - !Ref AWS::StackName
            - '-BuildWarFile'
      ServiceRole: 
        Fn::ImportValue: !Sub "${SecurityStack}-CodeBuildRole"
      Source:
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                java: corretto17
            pre_build:
              commands:
                - if [ -z "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then SRC_HASH=${CODEBUILD_SOURCE_VERSION}; else SRC_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}; fi
                - HASH=$(echo ${SRC_HASH} | cut -b 1-8)
            build:
              commands:
                - cd mvc
                - mvn compile package -DskipTests=true -q
                - aws s3 cp target/*.war s3://student-q-and-a/${HASH}.war
        GitCloneDepth: 1
        Location: https://github.com/wenzheluo/AscendingBackEndProject.git
        Type: GITHUB
  BuildImage:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Description: Build Image and push it to ECR
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ECR
            Value: wenzheluo.cofbxnshsp2o.us-east-1.rds.amazonaws.com/studentqna_db
      Name:
        Fn::Join:
          - ''
          - - !Ref AWS::StackName
            - '-BuildImage'
      ServiceRole: 
        Fn::ImportValue: !Sub "${SecurityStack}-CodeBuildRole"
      Source:
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email --region us-east-1)
                - if [ -z "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then SRC_HASH=${CODEBUILD_SOURCE_VERSION}; else SRC_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}; fi
                - IMAGE_TAG=$(echo ${SRC_HASH} | cut -b 1-8)
            build:
              commands:
                - cd ./ops/container/
                - aws s3 cp s3://student-q-and-a/${IMAGE_TAG}.war .
                - docker build -t "${ECR}:${IMAGE_TAG}" .
            post_build:
              commands:
                - docker push ${ECR}:${IMAGE_TAG}
                - echo "export TAG=${IMAGE_TAG}" > tag.sh
                - aws s3 cp tag.sh s3://student-q-and-a/ --quiet
        GitCloneDepth: 1
        Location: https://github.com/wenzheluo/AscendingBackEndProject.git
        Type: GITHUB
  UpdateCloudFormation:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Description: Update Cloudformation template
      Name:
        Fn::Join:
          - ''
          - - !Ref AWS::StackName
            - 'UpdateCloudFormation'
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: STACK_NAME
            Value: wenzheluo-ecs-studentqna
      ServiceRole:
        Fn::ImportValue: !Sub "${SecurityStack}-CodeBuildRole"
      TimeoutInMinutes: 60
      Source: 
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - aws s3 cp s3://student-q-and-a/tag.sh . --quiet
                - . ./tag.sh
            build:
              commands:
                - aws cloudformation update-stack --stack-name ${STACK_NAME} --use-previous-template --parameters ParameterKey=ELBStack,UsePreviousValue=true ParameterKey=SecurityStack,UsePreviousValue=true ParameterKey=Subnets,UsePreviousValue=true ParameterKey=JavaImageTag,ParameterValue=${TAG} ParameterKey=DBUsername,UsePreviousValue=true ParameterKey=DBPassword,UsePreviousValue=true
        GitCloneDepth: 1
        Location: https://github.com/wenzheluo/AscendingBackEndProject.git
        Type: GITHUB
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: 
        Fn::ImportValue: !Sub "${SecurityStack}-CodePipelineRole"
      ArtifactStore:
        Type: S3
        Location: student-q-and-a
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: wenzheluo
                Repo: AscendingBackEndProject
                Branch: master
                OAuthToken: !Ref OAuthToken
              OutputArtifacts:
                - Name: Source
              RunOrder: 1
        - Name: UnitTest
          Actions:
            - Name: UnitTest
              ActionTypeId: 
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref UnitTest
              InputArtifacts:
                - Name: Source
              RunOrder: 1
        - Name: BuildWarFile
          Actions:
            - Name: BuildWarFile
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref BuildWarFile
              InputArtifacts:
                - Name: Source
              RunOrder: 1
        - Name: BuildImage
          Actions:
            - Name: BuildImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref BuildImage
              InputArtifacts:
                - Name: Source
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: UpdateCloudFormation
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref UpdateCloudFormation
              InputArtifacts:
                - Name: Source
              RunOrder: 1
